ALTER TABLE listings
  ADD COLUMN IF NOT EXISTS finishing VARCHAR(100),
  ADD COLUMN IF NOT EXISTS ceiling_height NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS electricity_kw NUMERIC(8,2),
  ADD COLUMN IF NOT EXISTS utilities VARCHAR(500),
  ADD COLUMN IF NOT EXISTS road_line VARCHAR(50);